[package]
name = "arangodb-dump"
description = "Create resumable, manifest-described ArangoDB database dumps."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
arangodb-tools-core = { workspace = true }
arangodb-client = { workspace = true }
arangodb-storage = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
async-stream = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
sha2 = { workspace = true }
regex = { workspace = true }
