[package]
name = "arangodb-rdf"
description = "Bulk-load RDF data (N-Triples, Turtle, ...) into ArangoDB."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
arangodb-tools-core = { path = "../arangodb-tools-core" }
arangodb-import = { path = "../arangodb-import" }
